"""Create and run a tiny observational CSV benchmark.

From the repository root:

    python examples/custom_csv_data.py
"""

from __future__ import annotations

import math
from pathlib import Path

from lrdbench.runner import run_manifest_path


def write_example_csv(path: Path, *, n: int = 256) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        f.write("value\n")
        for i in range(n):
            trend = 0.0008 * i
            seasonal = 0.4 * math.sin(i / 11.0)
            slow_component = 0.15 * math.sin(i / 37.0)
            f.write(f"{trend + seasonal + slow_component:.8f}\n")


def write_example_manifest(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        """manifest_id: custom_csv_observational_v1
name: custom_csv_observational
description: Tiny observational benchmark generated by examples/custom_csv_data.py.
mode: observational
source:
  type: csv_series_index
  series:
    - record_id: example_csv_series
      path: data/example_series.csv
      value_column: value
estimators:
  - name: RS
    family: time_domain
    target_estimand: hurst_scaling_proxy
    supports_ci: true
    params:
      n_bootstrap: 32
      bootstrap_block_len: 12
      ci_levels: [0.95]
metrics:
  - validity_rate
  - runtime
  - name: ci_width
    levels: [0.95]
  - instability
  - preprocessing_sensitivity
preprocessing:
  sensitivity_eps: 1.0e-4
leaderboards:
  - name: observational_robustness
    mode: observational
    component_metrics: [instability, validity_rate, runtime]
    weights:
      instability: 0.5
      validity_rate: 0.3
      runtime: 0.2
    ranking_rule: weighted_rank
    tie_break_rule: best_primary_metric
report:
  formats: [html, csv]
  export_root: reports/custom_csv_data
seeds:
  global_seed: 20260426
execution:
  max_workers: 1
""",
        encoding="utf-8",
    )


def main() -> None:
    manifest_path = Path("custom_csv_observational.yaml")
    csv_path = Path("data/example_series.csv")
    write_example_csv(csv_path)
    write_example_manifest(manifest_path)

    out = run_manifest_path(manifest_path)
    print(f"csv_path={csv_path.resolve()}")
    print(f"manifest_path={manifest_path.resolve()}")
    print(f"run_id={out.run_id}")
    print(f"result_store={out.result_store_path}")
    if out.report_bundle and out.report_bundle.html_report_path:
        print(f"html_report={out.report_bundle.html_report_path}")
    if out.result_store_path:
        print(f"validate_output=lrdbench validate-output {out.result_store_path}")


if __name__ == "__main__":
    main()
